version: "3.8"
services:
  backend:
    image: "laviniaflorinagavril/students-management:16.9.2022.14.34.37"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev