version: "3.8"
services:
  backend:
    image: "laviniaflorinagavril/students-management:2.10.2022.12.13.5"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev