version: "3.8"
services:
  backend:
    image: "laviniaflorinagavril/students-management:9.10.2022.14.6.29"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev